Repository brazil-data-cube/bdc-catalog, pull requests merged in 2020-09, with the labels that each got.

#100 Add band source
  bdc_catalog/models/__init__.py
  bdc_catalog/models/band.py
  bdc_catalog/models/collection.py
Labels: enhancement

#102 Review for version 0.6.0
  docs/model/db-schema.png
  docs/model/db-schema.xml
  docs/sphinx/index.rst
  docs/sphinx/usage.rst
  run-tests.sh
Labels: release

#103 Fix diagram link after renaming repository.
  README.rst
Labels: bug

#104 Fix diagram link for branch 0.4.
  README.rst
Labels: bug

#106 Remove TimestampMixin from spatial_ref_sys
  bdc_catalog/models/item.py
Labels: bug

#108 Added last info in CHANGES.rst.
  CHANGES.rst
Labels: bug

#109 Move package version to alpha version of 0.8
  bdc_catalog/version.py
Labels: enhancement

#110 Increasing version on branch b-0.6
  bdc_catalog/version.py
Labels: enhancement

#113 Close #112 - Set lower case table comparison
  bdc_catalog/models/grid_ref_sys.py
Labels: bug

#117 fix trigger to update collection infos
  bdc_catalog/triggers/collection_statistics.sql
Labels: bug
