Repository brazil-data-cube/bdc-catalog, pull requests merged in 2020-08, with the labels that each got.

#41 Initial jsonschemas for bdc-db
  doc/spec/jsonschemas/application-metadata.json
  doc/spec/jsonschemas/band-metadata.json
  doc/spec/jsonschemas/collection-datacite.json
  doc/spec/jsonschemas/collection-instrument.json
  doc/spec/jsonschemas/collection-metadata.json
  doc/spec/jsonschemas/collection-temporal-composition-schema.json
  doc/spec/jsonschemas/item-assets.json
Labels: enhancement

#43 Rename python package bdc_db to bdc_catalog
  .gitignore
  bdc_catalog/__init__.py
  bdc_catalog/__main__.py
  bdc_catalog/cli.py
  bdc_catalog/ext.py
  bdc_catalog/jsonschemas/application-metadata.json
  bdc_catalog/jsonschemas/band-metadata.json
  bdc_catalog/jsonschemas/collection-datacite.json
  bdc_catalog/jsonschemas/collection-instrument.json
  bdc_catalog/jsonschemas/collection-metadata.json
  bdc_catalog/jsonschemas/collection-temporal-composition-schema.json
  bdc_catalog/jsonschemas/item-assets.json
  bdc_catalog/models/__init__.py
  bdc_catalog/models/application.py
  bdc_catalog/models/band.py
  bdc_catalog/models/base_sql.py
  bdc_catalog/models/collection.py
  bdc_catalog/models/composite_function_schema.py
  bdc_catalog/models/grs_schema.py
  bdc_catalog/models/item.py
  bdc_catalog/models/mime_type.py
  bdc_catalog/models/provider.py
  bdc_catalog/models/quicklook.py
  bdc_catalog/models/resolution_unit.py
  bdc_catalog/models/tile.py
  bdc_catalog/version.py
  bdc_db/__init__.py
  bdc_db/fixtures/cli.py
  bdc_db/fixtures/data/collections.json
  bdc_db/fixtures/data/composite_functions.json
  bdc_db/fixtures/data/grs_schemas.json
  bdc_db/fixtures/data/items.json
  bdc_db/fixtures/data/tiles.json
  bdc_db/models/collection_item.py
  bdc_db/models/collection_tile.py
  bdc_db/models/grs_schema.py
  bdc_db/models/raster_size_schema.py
  bdc_db/models/temporal_composition_schema.py
  doc/sphinx/api.rst
  doc/sphinx/conf.py
  examples/app.py
  pytest.ini
  setup.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_db.py
Labels: enhancement

#47 Add flag to control public collections and minor fix in Item index
  bdc_catalog/models/collection.py
  bdc_catalog/models/item.py
Labels: enhancement

#50 Add BDC-DB dependency
  INSTALL.rst
  RUNNING.rst
  bdc_catalog/alembic/8d0436d9ef21_add_migration_0_4_0.py
  bdc_catalog/cli.py
  bdc_catalog/ext.py
  bdc_catalog/models/base_sql.py
  setup.py
Labels: enhancement

#52 add srid field
  bdc_catalog/alembic/27edd5fc20d6_20200815_add_srid_field.py
  bdc_catalog/models/__init__.py
  bdc_catalog/models/item.py
Labels: enhancement

#56 Fixed diagram in the repository frontpage
  README.rst
Labels: documentation

#55 Review migrations
  RUNNING.rst
  bdc_catalog/alembic/27edd5fc20d6_20200815_add_srid_field.py
  bdc_catalog/alembic/8d0436d9ef21_add_migration_0_4_0.py
  bdc_catalog/models/base_sql.py
  bdc_catalog/models/grid_ref_sys.py
Labels: documentation

#59 Fix BDCCatalog extension init
  bdc_catalog/ext.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_db.py
Labels: bug

#60 Release version 0.4.0
  MANIFEST.in
  README.rst
  bdc_catalog/alembic/149deb59082a_v0_4_0.py
  bdc_catalog/models/collection.py
  bdc_catalog/models/grid_ref_sys.py
  docs/model/db-schema.png
  docs/model/db-schema.xml
  run-tests.sh
Labels: release

#61 Fix small typo to release Version 0.4.0
  README.rst
Labels: release

#62 Fix url in setup.py
  setup.py
Labels: bug

#72 JSONSchem review
  bdc_catalog/jsonschemas/band-metadata.json
  bdc_catalog/jsonschemas/collection-instrument.json
  bdc_catalog/jsonschemas/collection-metadata.json
  bdc_catalog/jsonschemas/item-assets.json
  bdc_catalog/jsonschemas/item-metadata.json
  bdc_catalog/models/application.py
Labels: enhancement

#74 Change version to varchar
  bdc_catalog/alembic/432e3447c36b_v0_4_0.py
  bdc_catalog/models/collection.py
  df75becb04b2_add_v0_4.py
Labels: enhancement

#85 Add timeline support and minimal trigger for bdc-catalog - 0.6.0
  MANIFEST.in
  RUNNING.rst
  bdc_catalog/alembic/f3f27ad116d2_timeline.py
  bdc_catalog/models/__init__.py
  bdc_catalog/models/collection.py
  bdc_catalog/models/timeline.py
  bdc_catalog/triggers/band_metadata_expression.sql
  bdc_catalog/triggers/collection_statistics.sql
  bdc_catalog/triggers/timeline.sql
  setup.py
Labels: enhancement

#87 Close #86 - Change Timestamp mixing to set default datetime on server side
  bdc_catalog/alembic/432e3447c36b_v0_4_0.py
  bdc_catalog/alembic/f3f27ad116d2_timeline.py
  bdc_catalog/models/base_sql.py
Labels: bug

#88 Merging Branch b-0.4 into master
  bdc_catalog/alembic/02d16d3da520_0_4_1.py
  bdc_catalog/models/collection.py
  bdc_catalog/models/grid_ref_sys.py
  bdc_catalog/models/item.py
  bdc_catalog/models/quicklook.py
Labels: enhancement, help wanted

#91 Merging version 0.4.1 fixes into master
  CHANGES.rst
  bdc_catalog/version.py
Labels: enhancement, release

#90 Add minimal multihash checksum utility
  bdc_catalog/utils.py
  setup.py
  tests/test_utils.py
Labels: enhancement

#95 Review for release 0.4.1
  CHANGES.rst
  bdc_catalog/version.py
Labels: enhancement, release

#96 Merge release 0.4.1 into master
  CHANGES.rst
  bdc_catalog/version.py
Labels: release

#97 Timeline
  MANIFEST.in
  RUNNING.rst
  bdc_catalog/alembic/02d16d3da520_0_4_1.py
  bdc_catalog/alembic/f3f27ad116d2_timeline.py
  bdc_catalog/models/__init__.py
  bdc_catalog/models/collection.py
  bdc_catalog/models/timeline.py
  bdc_catalog/triggers/band_metadata_expression.sql
  bdc_catalog/triggers/collection_statistics.sql
  bdc_catalog/triggers/timeline.sql
  setup.py
Labels: enhancement

#98 Minor changes - add checksum utility and set default datetime on server side
  bdc_catalog/alembic/432e3447c36b_v0_4_0.py
  bdc_catalog/alembic/f3f27ad116d2_timeline.py
  bdc_catalog/models/base_sql.py
  bdc_catalog/utils.py
  tests/test_utils.py
Labels: enhancement

#99 Fix misspelling postgresql; fix dependency error
  bdc_catalog/version.py
  setup.py
Labels: bug
