Repository brazil-data-cube/bdc-catalog, pull requests merged in 2020-11, with the labels that each got.

#119 issue #118
  setup.py
Labels: bug

#127 add new values in enum (collection_type)
  bdc_catalog/alembic/566a05da999d_edit_enums.py
  bdc_catalog/models/collection.py
Labels: enhancement

#128 Merge branch b-0.6 into master after release v0.6.4
  CHANGES.rst
  bdc_catalog/alembic/566a05da999d_edit_enums.py
  bdc_catalog/models/collection.py
  bdc_catalog/version.py
Labels: release
